### ISSUE TITLE
Unable to access through nginx reverse proxy - stuck at "Your Home Gallery is loading..."

### ISSUE THREAD

**Issue by JohanE67** [xemle/home-gallery#112]
I am running home gallery in a docker container setup and within my network it's all working as expected.

Now, for remote access, I am attempting to add home gallery to my remote proxy setup that I have running for several other web apps. I can see that the proxying is working, in a sense that the requests arrive at the home-gallery container. However, it stops at the initial "GET" request and nothing ever appears in the browser but the black screen with the house and text "Your Home Gallery is loading...".

Here's my docker-compose.yml:
```
version: "3.9"
services:
  api:
    # custom build via
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    container_name: home-gallery-api-server
    environment:
      # TensorflowJS backends
      # - cpu: slowest and best support
      # - wasm: good perfromance for arm64 and amd64 platforms
      # - node: best performance on amd64 platform
      #- BACKEND=cpu
      - BACKEND=wasm
      #- BACKEND=node
    restart: unless-stopped
  gallery:
    # custom build via
    #build: .
    image: xemle/home-gallery
    container_name: home-gallery
    restart: unless-stopped
    environment:
      - GALLERY_API_SERVER=http://home-gallery-api-server:3000
      - GALLERY_API_SERVER_CONCURRENT=1 # On low powered devices
      - GALLERY_API_SERVER_TIMEOUT=60 # On low powered devices
      - GALLERY_OPEN_BROWSER=false
      # Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
      - GALLERY_WATCH_POLL_INTERVAL=300
    volumes:
      - ./data:/data
      - /mnt/ssd/homegallery/storage:/data/storage
      # Mount your media directories below /data
      - /mnt/ssd/media/Photos:/data/Photos
        #- ${HOME}/Pictures:/data/Pictures
    ports:
      - "3030:3000"
    user: "${CURRENT_USER}"
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']
networks:
  default:
    name: rommenet
    external: true
```

And here's the relevant proxy setup (this is using the [LinuxServer/Swag](https://hub.docker.com/r/linuxserver/swag) container. Filename "proxy-confs/homegallery.subfolder.conf":

```
location /homegallery {
    return 301 $scheme://$host/homegallery/;
}

location ^~ /homegallery/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable for ldap auth (requires ldap-server.conf in the server block)
    #include /config/nginx/ldap-location.conf;

    # enable for Authelia (requires authelia-server.conf in the server block)
    #include /config/nginx/authelia-location.conf;

    # enable for Authentik (requires authentik-server.conf in the server block)
    #include /config/nginx/authentik-location.conf;

    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app home-gallery;
    set $upstream_port 3000;
    set $upstream_proto http;
    #proxy_set_header X-Real-IP $remote_addr;
    #proxy_set_header X-Forwarded-Host $host;
    #proxy_set_header X-Forwarded-Port $server_port;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    rewrite /homegallery(.*) $1 break;
}
```

When looking in the home-gallery container log, when attempting to open the gallery from the local network (http://192.168.1.10:3030) I see this:
```
[2024-01-04 14:12:25.816]: server.request 200 GET / 37ms
[2024-01-04 14:12:25.890]: server.request 200 GET /app.3cad02a2.css 61ms
[2024-01-04 14:12:25.986]: server.request 200 GET /App.228c57ae.js 149ms
[2024-01-04 14:12:26.029]: server.request 200 GET /fonts/fa-solid-900.a0feb384.woff2 13ms
[2024-01-04 14:12:26.035]: server.api.events Add new client ca36d6dd-a616-444d-9e97-dd8ebf2d2c9e
[2024-01-04 14:12:26.052]: server.request 200 GET /favicon.ico 15ms
[2024-01-04 14:12:26.053]: server.api.events Events file /data/config/events.db does not exist yet. It will be created on the first manual tag
[2024-01-04 14:12:26.056]: server.request warn 404 GET /api/events.json 11ms
[2024-01-04 14:12:26.063]: server.request 304 GET /api/database/tree/root.json 4ms
```
And the photostream appears in the browser.

When going through the reverse proxy (https://[my-domain]/homegallery/), I see only this:
`[2024-01-04 14:15:33.587]: server.request 200 GET / 37ms`
And am stuck at the "loading..." page.

The "rewrite" in the proxy conf appears to be working correctly, for when I retrieve a specific year for example (https://[my-domain]/homegallery/years/2015), I will see this in the log:
`[2024-01-04 14:19:56.539]: server.request 304 GET /years/2015 10ms`
And then nothing ... While this works fine when running on the local network.

I hope someone can give a hint on where this is going wrong.
Thanks,
Johan

**Comment by xemle** [comment]
Hi @JohanE67 

thank you for rising this issue.

The gallery is a Single Page Application (SPA) with URL based routing. So `https://[my-domain]/homegallery/years/2015` must be mapped correctly that `/homegallery` is a static prefix which is excluded from the SPA routing `/years/2015`.

To fix that the server command has a appropriate parameter `--base-path` for it:

```
$ ./gallery.js server -h
gallery.js server

Start web server

Options:
      --version                    Show version number                 [boolean]
  -l, --log-level                  Console log level
         [string] [choices: "trace", "debug", "info", "warn", "error", "silent"]
      --log-json-format            Log output format in json           [boolean]
  -L, --log-file                   Log file
      --log-file-level             Log file level
         [string] [choices: "trace", "debug", "info", "warn", "error"] [default:
                                                                        "debug"]
  -c, --config                     Configuration files
  -s, --storage                    Storage directory
  -d, --database                   Database filename
  -e, --events                     Events filename
  -H, --host                       Listening host IP address
                                                     [string] [default: 0.0.0.0]
  -p, --port                       Listening TCP port   [number] [default: 3000]
  -K, --key                        SSL key file
  -C, --cert                       SSL certificate file
  -b, --base-path                  Base path of static page. e.g. "/gallery"
                                                           [string] [default: /]
  -U, --user                       User and password for basic authentication.
                                   Format is username:password. Password schema
                                   can be {SHA}, otherwise it is plain   [array]
  -R, --ip-whitelist-rule, --rule  IP whitelist rule in format type:network.
                                   E.g. allow:192.168.0/24 or deny:all. First
                                   matching rule wins.                   [array]
      --open-browser               Open browser on server start
                                                       [boolean] [default: true]
      --remote-console-token       Enable remote console with given debug auth
                                   token                                [string]
      --watch-sources              Watch source files for changes
                                                       [boolean] [default: true]
  -h, --help                       Show help                           [boolean]
      --level                                                   [default: debug]
```

With your docker setup you can add an environment variable `GALLERY_BASE_PATH` to `/homegallery`.

When the base path is set you need to access the gallery always below `/homegallery`. So it is not possible to have a nginx proxy with `/homegallery` in front of it and parallel you access the gallery server directly within your home network with base path `/`.

**Comment by JohanE67** [comment]
So, I added the `GALLERY_BASE_PATH` variable and removed the `rewrite /homegallery(.*) $1 break;` from the proxy confguration. This does not solve the problem, however.

When I now go to `https://[my-domain]/homegallery/years/2015`, the log shows: 
`[2024-01-08 07:53:21.755]: server.request 304 GET /homegallery/years/2015 9ms`
But I still see only "Your Home Gallery is loading..."

When I go to `http://192.168.1.10:3030/homegallery/years/2015`, the log shows:
```
[2024-01-08 07:57:08.668]: server.request 304 GET /homegallery/years/2015 7ms
[2024-01-08 07:57:08.744]: server.api.events Add new client 39e059c3-3978-4872-99a8-443a6a08e3ff
[2024-01-08 07:57:08.751]: server.api.events Events file /data/config/events.db does not exist yet. It will be created on the first manual tag
[2024-01-08 07:57:08.754]: server.request warn 404 GET /api/events.json 7ms
[2024-01-08 07:57:08.767]: server.request 304 GET /api/database/tree/root.json 6ms
```
However, now the initial page is shown, not the year. Also, the url in the address bar switches back to plain `http://192.168.1.10:3030/`. Clicking to the year, it appears that `http://192.168.1.10:3030/years/2015` still works.

So it looks like the base-path directive is getting ignored??

**Comment by xemle** [comment]
Hi @JohanE67 

I've checked a simple example ant it seems that `GALLERY_BASE_PATH` requires a tailing slash. The base path `/homegallery/` ensures that every web resource gets the base path as prefix. Further the base path must be in sync with `nginx.conf` location directive.

Here is my working configuration:

```
Browser --> Nginx: http://localhost:3002/homegallery/index.html
Nginx --> gallery: http://gallery:3000/index.html
```


`docker-compose.yml`:
```
version: "3.9"
services:
  api:
    # custom build via
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    environment:
      # TensorflowJS backends
      # - cpu: slowest and best support
      # - wasm: good perfromance for arm64 and amd64 platforms
      # - node: best performance on amd64 platform
      #- BACKEND=cpu
      - BACKEND=wasm
      #- BACKEND=node
  gallery:
    # custom build via
    #build: .
    image: xemle/home-gallery
    environment:
      - GALLERY_API_SERVER=http://api:3000
      - GALLERY_API_SERVER_CONCURRENT=1 # for SoC devices like Rasperry Pi. Use 5 otherwise
      - GALLERY_API_SERVER_TIMEOUT=60 # for SoC devices like Rasperry Pi. Use 30 otherwise
      #- GALLERY_USE_NATIVE=ffprobe,ffmpeg,vipsthumbnail # On issues with sharp resizer
      - GALLERY_OPEN_BROWSER=false
      # Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
      - GALLERY_WATCH_POLL_INTERVAL=300
      - GALLERY_BASE_PATH=/homegallery/
    volumes:
      - ./data:/data
      # Mount your media directories below /data
      - ${HOME}/Pictures:/data/Pictures
    ports:
      - "3000:3000"
    user: "${CURRENT_USER}"
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']
  nginx:
    image: nginx:latest
    ports:
      - "3002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/html:/usr/share/nginx/html
    restart: always
```

`nginx.conf`:
```
events {
}

http {
    server {
        root /usr/share/nginx/html;
        location /homegallery {
            # Set to external URL
            return 307 http://localhost:3002/homegallery/;
        }        
        location /homegallery/ {
            proxy_pass http://gallery:3000/;
        }
    }
}
```

**Comment by bytebone** [comment]
after lots and lots and LOTS of trying, I cannot for the life of me get this to work. I'm using homegallery through docker with my own local API instance. Reverse Proxy is handled by Caddy, though in my testing I found that issues also arise when accessing the service directly via IP:3000. Configuration is done via the `gallery.config.yml` file mounted in `/data/config/`. Here's my server block from this file: 

```yml
server:
  #port: 3000
  #host: '0.0.0.0'
  # security configuration for https
  # key: '{configDir}/server.key'
  # cert: '{configDir}/server.crt'
  #openBrowser: true
  basePath: /gallery/
  watchSources: true
```

I have not found a way to confirm that the container is properly loading this configuration, but reading the file from a shell inside the container shows the correct settings. I have also not found a way to read the HTTP access logs of the app. **But** I have the access logs from my browser, when accessing the website with this config (presumably) loaded.

When loading `server:3000/` without a path, I load onto a "Your Home Gallery is loading..." screen that will never go away. Ressources loaded are
- html file at /
- /gallery/app.[...].css
- /gallery/App.[...].js
- /gallery/favicon.ico

This looks promising, but something in the JS must not properly load the following required ressources, so I get stuck on the loadscreen.

When loading `server:3000/gallery/` (where I would expect a working app), I am immediately redirected to `server:3000/`, which then loads all the UI and images and I have a working app in front of me. Ressources loaded (excerpt) are
- html file at /gallery/
- /app.[...].css
- /App.[...].js
- /fonts/[...]
- /api/events/[...]
- /files/[...]

In the entire list, I cannot find a **single** entry that was loaded from /gallery/. Not the images, not the static files, not the API calls. It all comes from the root, where I cannot even make contact when directly loading it. How can this be? I've spent hours trying to fix it, but cannot pinpoint the source of the issue. Note that whenever testing this, the cache was disabled through the developer tools, so I am discarding "cached file locations" or anything of the sort as a possible root.

Thanks in advance for any help you can provide.

**Comment by xemle** [comment]
Hi @bytebone 

thank you for your input and your patience so far. I am sorry that is was not successful until now.

>  I'm using homegallery through docker with my own local API instance. Reverse Proxy is handled by Caddy

I try to reproduce your setting. For your comment it is not 100% clear how your setup is created. So HomeGallery server, local API and Caddy are running inside docker via docker compose? I would like to reproduce this setting with Caddy - never played around with Caddy but heard it should be awesome. Would you mind to provide your `docker-compose.yml` and Caddy configuration?

Can you reproduce my previous provided `docker-compose.yml`with nginx? Is there a reason to use Caddy instead of nginx?

> though in my testing I found that issues also arise when accessing the service directly via IP:3000

You can only serve the server with one defined base path. Either `/` as default or `/gallery/` but not both at the same time due the SPA constrains and the `<base />` HTML tag which is not served dynamically.

If you use a base path the Browser sends a request with `http://<outer host>/gallery/` towards the proxy (Caddy, nginx, you name it). The proxy should strip the base path `/gallery/` and forwards the request to the internal service `http://<containe  ip>:3000`. The HTML response contains the `<base href="/gallery/" />` tag which is honored by subsequent requests. e.g. `http://<outer host>/gallery/App.[...].js`, which should reach the container server again as `http://<container ip>:3000/App.[...].js` through the proxy.

I tested the http proxy settings via curl and checked if the response is correct.

If you provide your `docker-compose.yml` I can have a look...

> I have also not found a way to read the HTTP access logs of the app

In the mounted `/data/config` volume you will find `gallery.log` which should contain requests information like (piped though jq):

```
{
  "level": 30,
  "time": 1651569028169,
  "pid": 51670,
  "hostname": "....",
  "module": "server.request",
  "req": {
    "id": 9,
    "method": "GET",
    "url": "/App.js",
    "query": {},
    "params": {},
    "headers": {
      "host": "localhost:3000",
      "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0",
      ...
    },
    "remoteAddress": "127.0.0.1",
    "remotePort": 58016
  },
  "res": {
    "statusCode": 200,
    "headers": {
      ...
    }
  },
  "responseTime": 40,
  "msg": "200 GET /App.js 40ms"
}
```

**Comment by bytebone** [comment]
Thank you for the elaborate and prompt response. 

> The proxy should strip the base path /gallery/ and forwards the request to the internal service

This, combined with the reminder that when using a base path I kind of have to access the app through the reverse proxy instead of the local IP, gave me the "click" i needed to make it work. I've updated my Caddyfile to remove the basePath before handing requests to the app, and _voilá!_ It works.

I'll still try to answer your questions as best as I can:

> your comment it is not 100% clear how your setup is created

Home Gallery App and API, as well as Caddy are all running on Docker. The two HG services are in one "HG-exclusive" network, the frontend app additionally joins the existing, Caddy-managed caddy network. 

compose.yml:
```yml
version: "3.9"
services:
  api:
    image: xemle/home-gallery-api-server
    container_name: homegallery-api
    environment:
      - BACKEND=node
    networks:
      - internal
  app:
    image: xemle/home-gallery
    container_name: homegallery-app
    environment:
      - GALLERY_API_SERVER=http://api:3000
      - GALLERY_API_SERVER_CONCURRENT=5 # for SoC devices like Rasperry Pi. Use 5 otherwise
      - GALLERY_API_SERVER_TIMEOUT=30 # for SoC devices like Rasperry Pi. Use 30 otherwise
      - GALLERY_OPEN_BROWSER=false
      - GALLERY_WATCH_POLL_INTERVAL=0
    volumes:
      - /mnt/user/appdata/homegallery:/data
      - /mnt/user/pictures1:/data/pictures/source1:ro
      - /mnt/user/pictures2:/data/pictures/source2:ro
    ports:
      - "3000:3000"
    networks:
      - internal
      - caddy
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']
    
networks:
  internal:
    name: hg_internal
  caddy:
    external: true
```
Caddyfile (before fixing it as described above):
```
http://my.domain.com {
    redir /gallery /gallery/
    handle /gallery/* {
            reverse_proxy http://homegallery-app:3000
    }
}
```
To fix the issue, replace the `handle` function with `handle_path`. The former passes the path onto the container (used in the case of *arr apps for example), while the latter strips it.

_(Sidenote: Caddy hands all traffic to a Cloudflare tunnel, which handles SSL encryption at the CF edge, which is why I'm completely skipping encryption on my server)_

Also good to know that this gallery.log has the access logs. I saw it plenty of times when editing the config, but never had the thought to actually look inside.
