### ISSUE TITLE
No api server? 

### ISSUE THREAD

**Issue by JohnnyDarks** [xemle/home-gallery#119]
Is it possible to build project with no api server at all?  My current use case does not have a need for a api server.

**Comment by xemle** [comment]
Hi @JohnnyDarks 

you can disable the api server calls via the `gallery.config.yml`:

```
extractor:
  apiServer:
    disable:
      - similarDetection
      - objectDetection
      - faceDetection
```
