### ISSUE TITLE
Error gallery.config.yml does not exist, when running init

### ISSUE THREAD

**Issue by mafrosis** [xemle/home-gallery#161]
Hello, I spent a few mins trying your project via docker - docker-compose file here:

```yaml
---
volumes:
  home-gallery: {}

services:
  api:
    image: xemle/home-gallery-api-server
    environment:
      - BACKEND=node

  gallery:
    image: xemle/home-gallery
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']
    environment:
      - GALLERY_API_SERVER=http://localhost:3000
      - GALLERY_API_SERVER_CONCURRENT=5
      - GALLERY_API_SERVER_TIMEOUT=30
      - GALLERY_OPEN_BROWSER=false
      - GALLERY_WATCH_POLL_INTERVAL=300
    volumes:
      - home-gallery:/data
      - /media/photos:/photos:ro
    ports:
      - 3000:3000
    depends_on:
      - api
```

On start up I get:
```
gallery-1  | [2024-11-24 02:14:57.355]: cli.run error Error: Error: Configuration file /data/config/gallery.config.yml does not exist
gallery-1 exited with code 0
```

So I tried to create a config file as directed in the docs, and got the same error - which seems like a bug?
```
$ docker compose run --rm gallery gallery run init --source /photos
Error: Error: Configuration file /data/config/gallery.config.yml does not exist
```
