### ISSUE TITLE
Exclude files

### ISSUE THREAD

**Issue by darrepac** [xemle/home-gallery#41]
Hi,

I don't have clear where and how I have to manage exclude files as stated here: https://docs.home-gallery.org/faq/index.html#how-long-does-the-initial-setup-take
Is it in gallery.config.yml ? how?

thanks

**Comment by xemle** [comment]
Yes, `gallery.config.yml` is the right place, which gives you some examples in its [comments](https://github.com/xemle/home-gallery/blob/282d2b3987c062b84b8b7a510067d9bed44f8615/gallery.config-example.yml#L48). Excluding files is a good place to limit the files to add to the gallery since the gallery only process/sees files which are in the file index.

You can add exlcude pattern for each source or you add an exclude file per source. The exlude pattern follows the [gitignore style](https://git-scm.com/docs/gitignore#_pattern_format). Further hole subdirectories can be skiped by an exclude file marker (eg an empty file called `.galleryignore`)

**Comment by darrepac** [comment]
I am probably not good understanding the doc, but I tried to follow what was in comment in the gallery.config.yml (just removing the # and putting the extension I wanted. So I put:
```
sources:
  - dir: '{baseDir}/Pictures'
    #index: '{configDir}/{configPrefix}{basename(dir)}.idx'
    # excludes are using gitignore patterns
    excludes:
      - *.mov
      - *.MOV
      - *.mp4
      - *.MP4
      - *.AVI
      - *.avi
```

But I launched run import, I got:
`cli.run error Error: YAMLReferenceError: Aliased anchor not found: .mov
`
