### ISSUE TITLE
API server adress in docker-compose

### ISSUE THREAD

**Issue by darrepac** [xemle/home-gallery#42]
Hi

I have seen the following error in the log:
```
{"level":40,"time":1656358316435,"pid":286,"hostname":"6546a3b0278e","module":"extractor.apiEntry","msg":"Too many errors. Skip processing of face detection"}
{"level":40,"time":1656358316436,"pid":286,"hostname":"6546a3b0278e","module":"extractor.apiEntry","err":{"type":"Error","message":"getaddrinfo ENOTFOUND api","stack":"Error: getaddrinfo ENOTFOUND api\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)","errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"api"},"msg":"Could not get face detection of a044226:Pictures:Photos_canon/2020/2020-07-23 XXX/IMG_0010.JPG from URL http://api:3000/faces: Error: getaddrinfo ENOTFOUND api"}
```

The api:3000 is what is put in the docker-compose.yml demo file. Shouldn't be localhost:3000 ?
Or the error is coming from elsewhere?

**Comment by xemle** [comment]
Mm. No. `http://api:3000` refers to the the api service of the other docker service. 

```
version: "3.9"
services:
  api:
    image: xemle/home-gallery-api-server
    environment:
      - BACKEND=wasm
```

See [docker-compose.yml](https://github.com/xemle/home-gallery/blob/master/docker-compose.yml)

Have you touched the service api part? Could you post your `docker-compose.yml`?

**Comment by darrepac** [comment]
ok I had a doubt, thanks for the clarifications. Here is my `docker-compose.yml`:
```
version: "3.9"
services:
  api:
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    environment:
      - BACKEND=node
    ports:
      - "3000"
  gallery:
    #build: .
    # Or use public image
    image: xemle/home-gallery
    environment:
      - GALLERY_API_SERVER=http://api:3000
    volumes:
      - /DATA/HomeGallery:/data
      - /NEWNAS/PHOTOS:/data/Pictures:ro
    ports:
      - "8080:3000"
    entrypoint: ['node', '/app/gallery.js', 'run', 'server']

```
