### ISSUE TITLE
Add support for webp source images

### ISSUE THREAD

**Issue by viktor02** [xemle/home-gallery#88]
Hi. For some reason after `./gallery run init -c config.yml` and `./gallery run server -c config.yml`, I have files found but not added to the database(and most likely no requests to the api server, but I'm not sure).

I also tried without native tools(before this log), but the result is the same.

*Logs*: https://pastebin.com/Enu6LWLe
*Files in my library*: .webp  and .mp4
*Config (from cli)*:
```
baseDir: /opt/home-gallery/
configDir: /opt/home-gallery//config
cacheDir: /opt/home-gallery//cache/
sources:
  - index: /opt/home-gallery//config/PhotoArchive.idx
    offline: false
    excludeIfPresent: .galleryignore
    dir: /srv/big/photos/PhotoArchive
extractor:
  apiServer:
    url: http://192.168.10.2:3001
    concurrent: 5
  useNative:
    - convert
    - ffprobe
    - ffmpeg
storage:
  dir: /opt/home-gallery//cache//storage
database:
  file: /opt/home-gallery//config/database.db
  maxMemory: 4096
events:
  file: /opt/home-gallery//config/events.db
server:
  host: 0.0.0.0
  port: 3000
  openBrowser: true
  basePath: /
  watchSources: true
logger:
  - type: console
    level: trace
  - type: file
    level: debug
    file: /opt/home-gallery//config/gallery.log
configPrefix: ""
```
