### ISSUE TITLE
Docker image for linux/arm/v7 broken

### ISSUE THREAD

**Issue by arbesulo** [xemle/home-gallery#9]
Hi! I'm trying to start the server and the api via docker-compose on my raspberry pi 4, but docker seems to have some problems:

> Pulling api (xemle/home-gallery-api-server:dc9de695)...
> latest: Pulling from xemle/home-gallery-api-server
> ERROR: no matching manifest for linux/arm/v7 in the manifest list entries

 docker --version
Docker version 20.10.7, build f0df350

docker-compose.yml

```yml
version: "3.9"
services:
  api:
    image: xemle/home-gallery-api-server
    environment:
      # TensorflowJS backends: cpu, wasm and node. Use wasm
      # if you have troubles.
      #- BACKEND=cpu
      - BACKEND=wasm
      #- BACKEND=node
    ports:
      - "3000"
  gallery:
    image: xemle/home-gallery
    environment:
      - GALLERY_API_SERVER=http://api:3000
    volumes:
      - ./data:/data
      # Mount your media directories below /data
      - ${HOME}/Pictures:/data/Pictures
    ports:
      - "3000:3000"
    user: "1000:1000"
    entrypoint: ['node', '/app/gallery.js', 'run', 'server']
```

thanks in advance!
